name: example
description: A new Flutter project.

Author: Ketan Choyal <ketanchoyal@gmail.com>
homepage: https://github.com/ketanchoyal/

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_search:
    path: ../

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
