name: mapbox_search
description: A Flutter package for place search using MapBox Api and for Static map image
version: 2.0.0-dev.1
authors:
  - Ketan Choyal <ketanchoyal@gmail.com>
  - Daniel Oliveira <shinayser@gmail.com>
homepage: https://github.com/ketanchoyal/mapbox_search/tree/dev

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http: any
  color: ^2.1.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.3