name: mapbox_search
description: A Flutter package for place search using MapBox Api and for Static map image
version: 1.0.0

author: Ketan Choyal <ketanchoyal@gmail.com>
homepage: https://github.com/ketanchoyal/mapbox_search

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true