name: mapbox_search
description: A Flutter package for place search using MapBox Api and for Static map image
version: 2.0.1+1

homepage: https://github.com/ketanchoyal/mapbox_search/tree/master

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  color: ^2.1.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.3
